### ISSUE TITLE
Custom colors are not supported in the card header

### ISSUE THREAD

**Issue by twwch** [galaxy-book/feishu-sdk-golang#14]
https://open.feishu.cn/document/ukTMukTMukTM/ukTNwUjL5UDM14SO1ATN
![image](https://user-images.githubusercontent.com/44161003/98438977-36b2df00-2129-11eb-8245-0a5794ccccf4.png)

**Comment by ainilili** [comment]
fix with this commit: [https://github.com/galaxy-book/feishu-sdk-golang/commit/d3ac81cf02ea74629a3721609122d94cf64d8d72](https://github.com/galaxy-book/feishu-sdk-golang/commit/d3ac81cf02ea74629a3721609122d94cf64d8d72)

release v0.3.4 was supported this field.

**Comment by suhanyujie** [comment]
We can close this issue now.

**Comment by twwch** [comment]
thank you  very much------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Nico&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月5日(星期六) 下午5:13
收件人:&nbsp;&quot;galaxy-book/feishu-sdk-golang&quot;<feishu-sdk-golang@noreply.github.com&gt;;
抄送:&nbsp;&quot;twwch&quot;<2329095893@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [galaxy-book/feishu-sdk-golang] Custom colors are not supported in the card header (#14)
