### ISSUE TITLE
What does `vo` mean?

### ISSUE THREAD

**Issue by HuuLane** [galaxy-book/feishu-sdk-golang#15]
感谢大佬的 sdk, 就是想问一下 vo 的字面意思指的是什么? (捂脸笑

https://github.com/galaxy-book/feishu-sdk-golang/tree/master/core/model/vo

**Comment by suhanyujie** [comment]
Java 里的概念吧，VO 代指值对象（value object）,有些地方也称变量对象（var object）。@ainilili

**Comment by ainilili** [comment]
view object, 视图对象，指对外接口的数据格式封装

**Comment by mvpsince** [comment]
正好在用go重写飞书相关，赞！有没有讨论群

**Comment by ainilili** [comment]
> 正好在用go重写飞书相关，赞！有没有讨论群

暂时莫得
